/*
 * eSuite API - OpenAPI 3.0
 * This is a sample eSuite API Server based on the OpenAPI 3.0 specification.
 *
 * OpenAPI spec version: 11.29.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.40
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "./ApiClient.js";
import { Account } from "./model/Account.js";
import { AccountApi } from "./api/AccountApi.js";

/**
 * This_is_a_sample_eSuite_API_Server_based_on_the_OpenAPI_3_0_specification_.<br>
 * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
 * <p>
 * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
 * <pre>
 * var ESuiteApiOpenApi30 = require('index'); // See note below*.
 * var xxxSvc = new ESuiteApiOpenApi30.XxxApi(); // Allocate the API class we're going to use.
 * var yyyModel = new ESuiteApiOpenApi30.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
 * and put the application logic within the callback function.</em>
 * </p>
 * <p>
 * A non-AMD browser application (discouraged) might do something like this:
 * <pre>
 * var xxxSvc = new ESuiteApiOpenApi30.XxxApi(); // Allocate the API class we're going to use.
 * var yyy = new ESuiteApiOpenApi30.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * </p>
 * @module index
 * @version 11.29.11
 */
export {
  /**
   * The ApiClient constructor.
   * @property {module:ApiClient}
   */
  ApiClient,

  /**
   * The Account model constructor.
   * @property {module:model/Account}
   */
  Account,

  /**
   * The AccountApi service constructor.
   * @property {module:api/AccountApi}
   */
  AccountApi,
};
